[package]
description = "Provides simple TTY-based interface capabilities including partial re-renders of multi-line displays."
authors = ["Daniel Way <contact@danieldway.com>"]
name = "tty-interface"
version = "3.0.0"
license = "MIT"
edition = "2021"
repository = "https://github.com/danielway/tty-interface"
exclude = [".github"]

# This is necessary for functional testing in CI. See https://github.com/dankamongmen/notcurses/issues/766
[alias]
t = "test -- --test-threads 1"

[dependencies]
crossterm = "0.25.0"
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dev-dependencies]
vt100 = "0.15.1"
